# Generated by Django 6.0.4 on 2026-05-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='name',
            field=models.CharField(default='Assessment', max_length=200),
            preserve_default=False,
        ),
    ]
