# Generated by Django 6.0.4 on 2026-05-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_assessment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['date', 'name'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['assessment__date', 'student__last_name', 'student__first_name'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
    ]
