# Generated by Django 6.0.4 on 2026-04-28 23:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'course')},
        ),
    ]
