# Generated by Django 6.0.4 on 2026-04-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_unique_together_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('subject', 'date', 'start_time')},
        ),
    ]
